-   hosts:  localhost

    gather_facts: true
    
    vars: 
        usuario: "felipe"
        home_usuario: "/home/felipe"

    pre_tasks:
        -   name: Pre tarea 1
            debug:
                msg: soy la pre tarea 1

        -   name: Pre tarea 2
            debug:
                msg: soy la pre tarea 2
                
        -   name: Pre tarea 3
            debug:
                var: ansible_facts     
        
        -   name: Pre tarea 4
            debug:
                msg: "Sistema operativo: {{ ansible_facts.distribution }}" 
                
        -   name: Pre tarea 5
            debug:
                msg: "Memoria swap libre: {{ ansible_facts.memory_mb.swap.free }}"    
                
        -   name: Pre tarea 6
            debug:
                msg: "Tipo del 2º CPU: {{ ansible_facts.processor[5] }}" 
                
        -   name: Pre tarea 7
            debug:
                msg: |- 
                         Un calculo: {{ 3 + 4 }}
                         Memoria en uso: {{ ansible_facts.memory_mb.real.total - ansible_facts.memory_mb.real.free }}
                         
        -   name: Pre tarea 8
            debug:
                msg: "Tipo del 2º CPU: {{ ansible_facts.processor[5] | upper }}" 
        #-   name: Pre tarea 3
         #   debug:
          #      msg: Quiero mostrar los facts de mi host {{ ansible_facts }}
    tasks: 
        -   name: Tarea 1
            debug:
                msg: soy la tarea 1
                
        -   name: Tarea 2
            debug:
                msg: soy la tarea 2
                
        -   name: Asegurarme que hay un usuario 'felipe' con una configuración
            user:
                name:   "{{ usuario }}"
                home:   "{{ home_usuario }}"
                state:  present
            become:     true
                
        -   name: Quiero saber la version de nginx que tengo instalada
            shell:
                cmd:        nginx --version
            changed_when:   false
            failed_when:    false
            
        -   name: Tarea 3
            debug:
                msg: Soy una tarea condicional que se ejecuta solo en máquinas UBUNTU
            when: ansible_facts.distribution == "Ubuntu"
            
        -   name: Tarea 4
            debug:
                msg: Soy una tarea condicional que se ejecuta solo en máquinas QUE NO SON UBUNTU
            when: ansible_facts.distribution != "Ubuntu"
            
        -   name: Tarea 5 
            debug: 
                msg: Esta es una tarea que esta instalando unas cosas
            tags:
                - instalacion
                
        -   name: Tarea 6 
            debug: 
                msg: Esta es una tarea que esta configurando unas cosas
            tags:
                - configuracion      
                
        -   name: Tarea 7 
            debug: 
                msg: Esta es una tarea que esta probando unas cosas
            tags:
                - test
                - always
                
        -   name: Tarea 8
            debug: 
                msg: Esta es una tarea que va a invocar un handlers
            notify: Handler 1
            changed_when: true
            
        -   name: Tarea 9
            debug: 
                msg: Esta es una tarea que va a invocar un handlers
            notify: Handler 1
            changed_when: true    
            
        -   name: Tarea 10
            debug: 
                msg: Esta es otra tarea
                
        -   name: Tarea 11
            debug: 
                msg: Esta es una tarea que va a invocar un EVENTO
            notify: SERVIDOR_RECONFIGURADO 
            changed_when: true        

    post_tasks:
        -   name: Post tarea 1
            debug:
                msg: soy la post tarea 1
                
        -   name: Post tarea 2
            debug:
                msg: soy la post tarea 2
        -   name: Conjunto de tareas relacionadas
            block:
                -   name: Tarea 1 del bloque
                    debug:
                        msg: Soy la Tarea 1 del bloque
                    failed_when: true
                -   name: Tarea 2 del bloque
                    debug:
                        msg: Soy la Tarea 2 del bloque
                        
            rescue:
                -   name: Tarea 1 del rescue
                    debug:
                        msg: Soy la tarea 1 del rescue
                -   name: Tarea 2 del rescue
                    debug:
                        msg: Soy la tarea 2 del rescue
                        
            always:
                -   name: Tarea 1 del always
                    debug:
                        msg: Soy la tarea 1 de always
                        
        -   name: Pos Tarea 3
            debug:
                msg: soy la post tarea 3
            failed_when:    true
            ignore_errors:  true
                
        -   name: Pos Tarea 4
            debug:
                msg: Soy la post tarea 4         
                        
        -   name: Quiero saber ka vesión de ansible que tengo instalado
            shell:
                cmd: ansible --version
            changed_when:   false
            failed_when:    false
            register: version_ansible
            
        -   name: Mostrar la versión que tengo de ansible
            debug:
                msg: |
                    la version de ansible es: {{ version_ansible.stdout }}
                    la version de ansible es: {{ version_ansible.stdout_lines[0] }}
                    return code: {{ version_ansible.rc }}
                    
        -   name: Ansible no esta instalado
            debug:
                msg: Ansible no esta instalado
            when: version_ansible > 0
            
        -   name: Quiero saber la versión de nginx que tengo instalado
            shell:
                cmd: nginx --version
            changed_when:   false
            failed_when:    false
            register: version_nginx
    
        -   name: Nginx no esta instalado
            debug:
                msg: Nginx no esta instalado
            when: version_nginx > 0   
            
        -   name: Quiero saber la versión de nginx que tengo instalado
            shell:
                cmd: nginx --version
            changed_when:   false
            register: version_nginx_2
            ignore_errors: true
            
        -   name: Nginx no esta instalado
            debug:
                msg: Nginx no esta instalado
            when: version_nginx_2 is failed
            
        -   name: comprobar disponibilidad de nginx
            block:
                -   name: comprobar la version instalada de nginx
                    shell: 
                        cmd: nginx --version
            rescue:
                -   name: Nginx no está instalado
                    debug:
                        msg: Nginx no está instalado
                        
        -   debug:
                var: version_nginx_2
                
        -   name: Quiero saber la versión que tengo instalada de unos programas
            shell:
                cmd: "{{ item }} --version"
            changed_when: false
            failed_when: false
            loop:
                - ansible
                - nginx
                - curl
            register: versiones
            
        -   debug:
                var: versiones
                
        -   name: Quiero saber la version que tengo instalada de git
            shell:
                cmd: git --version
            register: version_git
            
        -   debug:
                var: version_git
                
        -   debug:
                msg: "La version del programa instalada del programa {{ item.item }} es: {{ item.stdout_lines.0 }}"
            when: item.rc == 0
            loop: "{{ versiones.results }}"
                
    handlers:
        -   name: Handler 1
            debug:
                msg: Soy el Handler 1
            listen:
                - SERVIDOR_RECONFIGURADO
                
        -   name: Handler 2
            debug:
                msg: Soy el Handler 2   
            listen:
                - SERVIDOR_RECONFIGURADO
                
        -   name: Handler 3
            debug:
                msg: Soy el Handler 3   
            listen:
                - SERVIDOR_RECONFIGURADO