-   hosts:  localhost

    gather_facts: true
    
    vars: 
        usuario: "felipe"
        home_usuario: "/home/felipe"

    pre_tasks:
        -   name: Pre tarea 1
            debug:
                msg: soy la pre tarea 1

        -   name: Pre tarea 2
            debug:
                msg: soy la pre tarea 2
                
        -   name: Pre tarea 3
            debug:
                var: ansible_facts     
        
        -   name: Pre tarea 4
            debug:
                msg: "Sistema operativo: {{ ansible_facts.distribution }}" 
                
        -   name: Pre tarea 5
            debug:
                msg: "Memoria swap libre: {{ ansible_facts.memory_mb.swap.free }}"    
                
        -   name: Pre tarea 6
            debug:
                msg: "Tipo del 2º CPU: {{ ansible_facts.processor[5] }}" 
                
        -   name: Pre tarea 7
            debug:
                msg: |- 
                         Un calculo: {{ 3 + 4 }}
                         Memoria en uso: {{ ansible_facts.memory_mb.real.total - ansible_facts.memory_mb.real.free }}
                         
        -   name: Pre tarea 8
            debug:
                msg: "Tipo del 2º CPU: {{ ansible_facts.processor[5] | upper }}" 
        #-   name: Pre tarea 3
         #   debug:
          #      msg: Quiero mostrar los facts de mi host {{ ansible_facts }}
    tasks: 
        -   name: Tarea 1
            debug:
                msg: soy la tarea 1
                
        -   name: Tarea 2
            debug:
                msg: soy la tarea 2
                
        -   name: Asegurarme que hay un usuario 'felipe' con una configuración
            user:
                name:   "{{ usuario }}"
                home:   "{{ home_usuario }}"
                state:  present
            become:     true
                
        -   name: Quiero saber la version de nginx que tengo instalada
            shell:
                cmd:        nginx --version
            changed_when:   false
            failed_when:    false
            
        -   name: Tarea 3
            debug:
                msg: Soy una tarea condicional que se ejecuta solo en máquinas UBUNTU
            when: ansible_facts.distribution == "Ubuntu"
            
        -   name: Tarea 4
            debug:
                msg: Soy una tarea condicional que se ejecuta solo en máquinas QUE NO SON UBUNTU
            when: ansible_facts.distribution != "Ubuntu"
            
        -   name: Tarea 5 
            debug: 
                msg: Esta es una tarea que esta instalando unas cosas
            tags:
                - instalacion
                
        -   name: Tarea 6 
            debug: 
                msg: Esta es una tarea que esta configurando unas cosas
            tags:
                - configuracion      
                
        -   name: Tarea 7 
            debug: 
                msg: Esta es una tarea que esta probando unas cosas
            tags:
                - test
                - always
                
        -   name: Tarea 8
            debug: 
                msg: Esta es una tarea que va a invocar un handlers
            notify: Handler 1
            changed_when: true
            
        -   name: Tarea 9
            debug: 
                msg: Esta es una tarea que va a invocar un handlers
            notify: Handler 1
            changed_when: true    
            
        -   name: Tarea 10
            debug: 
                msg: Esta es otra tarea
                
        -   name: Tarea 11
            debug: 
                msg: Esta es una tarea que va a invocar un EVENTO
            notify: SERVIDOR_RECONFIGURADO 
            changed_when: true        

    post_tasks:
        -   name: Post tarea 1
            debug:
                msg: soy la post tarea 1
                
        -   name: Post tarea 2
            debug:
                msg: soy la post tarea 2
                
    handlers:
    
        -   name: Handler 1
            debug:
                msg: Soy el Handler 1
            listen:
                - SERVIDOR_RECONFIGURADO
                
        -   name: Handler 2
            debug:
                msg: Soy el Handler 2   
            listen:
                - SERVIDOR_RECONFIGURADO
                
        -   name: Handler 3
            debug:
                msg: Soy el Handler 3   
            listen:
                - SERVIDOR_RECONFIGURADO